package javaNestedClassExample;

//Anonymous Inner Class
//->A class that have no name and its name is generated by the compiler automatically.
// It is uesd if we want to provide method of class or interface.
abstract class Vehicle {
	abstract void start();

	abstract void showName();
}

public class AnonymousInnerClass {
	public static void main(String[] args) {
		Vehicle v = new Vehicle() {

			@Override
			void start() {
				System.out.println("Starts with Key");

			}

			@Override
			void showName() {
				System.out.println("Tata Nexon");

			}
		};
		v.start();
		v.showName();
	}
}
